### ISSUE TITLE
Thumbnail Support

### ISSUE THREAD

**Issue by MitchTalmadge** [nor0x/OpenPanels#1]
Hey great repo and website! I would recommend if possible that the images which are displayed be low resolution thumbnails, but link to the full image on click. It’s currently much too slow to browse on my phone. 

Thanks!

**Comment by nor0x** [comment]
with 0131d0dc1d41fbcb34687f63bbc624ba3d51d7a0 thumbnails are displayed (for those images where I could find according data)
